### ISSUE TITLE
Cann't use Ctrl+C, Ctrl+V

### ISSUE THREAD

**Issue by m2maomao** [mohzy83/NppMarkdownPanel#27]
when I mouse select some text in doc,I just want copy line what I selected,but when I parse,it's not run.

**Comment by PetbkA** [comment]
Couldn't fully understand your description, but I guess I'm experiencing the same problem: copying text via Ctrl+V doesn't work, though it works via right mouse button. I guess it's because hotkeys are focused to work inside _NP++_, not the panel. It allows you to show/hide panel on hotkey, but copying text must be done from NP++ itself too, not from the panel

**Comment by mohzy83** [comment]
The copy event (CTRL+C) is captured by npp and is not passed to the underlying IE (which is embedded).
Best workaround is to use right click "Copy".
